export const MUNICIPIOS_PERNAMBUCO = new Set([
  "ABREU E LIMA", "AFOGADOS DA INGAZEIRA", "AFRÂNIO", "AGRESTINA", "ÁGUA PRETA",
  "ÁGUAS BELAS", "ALAGOINHA", "ALIANÇA", "ALTINHO", "AMARAJI", "ANGELIM",
  "ARAÇOIABA", "ARARIPINA", "ARCOVERDE", "BARRA DE GUABIRABA", "BARREIROS",
  "BELÉM DE MARIA", "BELÉM DE SÃO FRANCISCO", "BELO JARDIM", "BETÂNIA",
  "BEZERROS", "BODOCÓ", "BOM CONSELHO", "BOM JARDIM", "BONITO", "BREJÃO",
  "BREJINHO", "BREJO DA MADRE DE DEUS", "BUENOS AIRES", "BUÍQUE",
  "CABO DE SANTO AGOSTINHO", "CABROBÓ", "CACHOEIRINHA", "CAETÉS", "CALÇADO",
  "CALUMBI", "CAMARAGIBE", "CAMOCIM DE SÃO FÉLIX", "CAMUTANGA", "CANHOTINHO",
  "CAPOEIRAS", "CARNAÍBA", "CARNAUBEIRA DA PENHA", "CARPINA", "CARUARU",
  "CASINHAS", "CATENDE", "CEDRO", "CHÃ DE ALEGRIA", "CHÃ GRANDE", "CONDADO",
  "CORRENTES", "CORTÊS", "CUMARU", "CUPIRA", "CUSTÓDIA", "DORMENTES",
  "ESCADA", "EXU", "FEIRA NOVA", "FERNANDO DE NORONHA", "FERREIROS", "FLORES",
  "FLORESTA", "FREI MIGUELINHO", "GAMELEIRA", "GARANHUNS", "GLÓRIA DO GOITÁ",
  "GOIANA", "GRANITO", "GRAVATÁ", "IATI", "IBIMIRIM", "IBIRAJUBA", "IGARASSU",
  "IGUARACI", "INAJÁ", "INGAZEIRA", "IPOJUCA", "IPUBI", "ITACURUBA", "ITAÍBA",
  "ILHA DE ITAMARACÁ", "ITAMBÉ", "ITAPETIM", "ITAPISSUMA", "ITAQUITINGA",
  "JABOATÃO DOS GUARARAPES", "JAQUEIRA", "JATAÚBA", "JATOBÁ", "JOÃO ALFREDO",
  "JOAQUIM NABUCO", "JUCATI", "JUPI", "JUREMA", "LAGOA DO CARRO",
  "LAGOA DO ITAENGA", "LAGOA DO OURO", "LAGOA DOS GATOS", "LAGOA GRANDE",
  "LAJEDO", "LIMOEIRO", "MACAPARANA", "MACHADOS", "MANARI", "MARAIAL",
  "MIRANDIBA", "MOREILÂNDIA", "MORENO", "NAZARÉ DA MATA", "OLINDA", "OROBÓ",
  "OROCÓ", "OURICURI", "PALMARES", "PALMEIRINA", "PANELAS", "PARANATAMA",
  "PARNAMIRIM", "PASSIRA", "PAUDALHO", "PAULISTA", "PEDRA", "PESQUEIRA",
  "PETROLÂNDIA", "PETROLINA", "POÇÃO", "POMBOS", "PRIMAVERA", "QUIPAPÁ",
  "QUIXABA", "RECIFE", "RIACHO DAS ALMAS", "RIBEIRÃO", "RIO FORMOSO", "SAIRÉ",
  "SALGADINHO", "SALGUEIRO", "SALOÁ", "SANHARÓ", "SANTA CRUZ",
  "SANTA CRUZ DA BAIXA VERDE", "SANTA CRUZ DO CAPIBARIBE", "SANTA FILOMENA",
  "SANTA MARIA DA BOA VISTA", "SANTA MARIA DO CAMBUCÁ", "SANTA TEREZINHA",
  "SÃO BENEDITO DO SUL", "SÃO BENTO DO UNA", "SÃO CAITANO", "SÃO JOÃO",
  "SÃO JOAQUIM DO MONTE", "SÃO JOSÉ DA COROA GRANDE", "SÃO JOSÉ DO BELMONTE",
  "SÃO JOSÉ DO EGITO", "SÃO LOURENÇO DA MATA", "SÃO VICENTE FERRER",
  "SERRA TALHADA", "SERRITA", "SERTÂNIA", "SIRINHAÉM", "SOLIDÃO", "SURUBIM",
  "TABIRA", "TACAIMBÓ", "TACARATU", "TAMANDARÉ", "TAQUARITINGA DO NORTE",
  "TEREZINHA", "TERRA NOVA", "TIMBAÚBA", "TORITAMA", "TRACUNHAÉM", "TRINDADE",
  "TRIUNFO", "TUPANATINGA", "TUPARETAMA", "VENTUROSA", "VERDEJANTE",
  "VERTENTE DO LÉRIO", "VERTENTES", "VICÊNCIA", "VITÓRIA DE SANTO ANTÃO", "XEXÉU",
]);

export const normalizarMunicipio = (texto = "") =>
  texto
    .toString()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toUpperCase()
    .replace(/[^A-Z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const MUNICIPIOS_CANONICOS = new Map(
  [...MUNICIPIOS_PERNAMBUCO].map((nomeOficial) => [
    normalizarMunicipio(nomeOficial),
    nomeOficial,
  ])
);

const ALIASES_MUNICIPIOS = {
  "LAGOA DE ITAENGA": "LAGOA DO ITAENGA",
  "ITAMARACA": "ILHA DE ITAMARACÁ",
  "ITAMARACÁ": "ILHA DE ITAMARACÁ",
  "BELEM DE SAO FRANCISCO": "BELÉM DE SÃO FRANCISCO",
  "BELEM DO SAO FRANCISCO": "BELÉM DE SÃO FRANCISCO",
  "BELEM SAO FRANCISCO": "BELÉM DE SÃO FRANCISCO",
  "NAZARE DE MATA": "NAZARÉ DA MATA",
  "RIBEIRAO": "RIBEIRÃO",
  "IGUARACY": "IGUARACI",
  "INAJA": "INAJÁ",
  "SAO CAETANO": "SÃO CAITANO",
  "JABOATAO DOS GUARAPES": "JABOATÃO DOS GUARARAPES",
  "JABOATAO DOS GUARARAPES": "JABOATÃO DOS GUARARAPES",
  "JABAOTAO DOS GUARARAPES": "JABOATÃO DOS GUARARAPES",
  "VITORIA DE SANTO ANTAO": "VITÓRIA DE SANTO ANTÃO",
  "VITORA DE SANTO ANTAO": "VITÓRIA DE SANTO ANTÃO",
  "BREJO DA MADRE DEUS": "BREJO DA MADRE DE DEUS",
  "CARNAUBEIRA DAPENHA": "CARNAUBEIRA DA PENHA",
  "JOAQUIMNABUCO": "JOAQUIM NABUCO",
  "BARRADE GUABIRABA": "BARRA DE GUABIRABA",
  "GLORIADO GOITA": "GLÓRIA DO GOITÁ",
  "SANTA MARIA DO CUMBUCA": "SANTA MARIA DO CAMBUCÁ",
  "AFOGADOS DA INGAZEIRAS": "AFOGADOS DA INGAZEIRA",
};

export const canonizarMunicipio = (texto = "") => {
  const chave = normalizarMunicipio(texto);

  if (!chave || chave === "NAO IDENTIFICADO") return "NÃO IDENTIFICADO";

  const aliasResolvido = ALIASES_MUNICIPIOS[chave];
  if (aliasResolvido) return aliasResolvido;

  return MUNICIPIOS_CANONICOS.get(chave) || "NÃO IDENTIFICADO";
};

export const municipioEhDePernambuco = (municipio) => {
  return canonizarMunicipio(municipio) !== "NÃO IDENTIFICADO";
};

export const filtrarRegistrosDePernambuco = (registros = []) =>
  registros.filter((item) =>
    municipioEhDePernambuco(item?.municipioNormalizado || item?.municipio)
  );